// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdqlitbpvaypuepnupmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkcWxpdGJwdmF5cHVlcG51cG13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDY2ODMsImV4cCI6MjA2NDE4MjY4M30.h9a1nys2JPspf552tSnkEQXqj8RkHWYwWo2bxyN3ho0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);